#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config focused_border_color \#d79921

bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Arandr state=floating follow=on
bspc rule -a Zathura state=tiled follow=on

# focus desktop 1
bspc desktop -f '^1'

# Autostart
feh --bg-scale ~/Images/everest.jpg
firefox-esr &
